In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


## Zero Dimension

In [3]:
import numpy as np
arr=np.array(25)
print(arr)
print(type(arr))
print(arr.ndim)

25
<class 'numpy.ndarray'>
0


## One Dimension

In [5]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


## Two Dimension

In [7]:
import numpy as np
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr)
print(type(arr))
print(arr.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
<class 'numpy.ndarray'>
2


## Three Dimension

In [9]:
import numpy as np
arr=np.array([[[1,2,3],[5,6,7]],[[8,9,10],[3,4,5]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[ 1  2  3]
  [ 5  6  7]]

 [[ 8  9 10]
  [ 3  4  5]]]
<class 'numpy.ndarray'>
3


## Indexing (one dim,two dim,three dim)

In [11]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[1])

2


In [12]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,3])

4


In [13]:
import numpy as np
arr=np.array([[[1,2,3],[5,6,7]],[[8,9,10],[3,4,5]]])
print(arr[1,1,2])
print(arr[0,1,1])

5
6


# Slicing

### One dim

In [16]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


### Two dim

In [18]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0:2,1:4])

[7 8 9]
[[2 3 4]
 [7 8 9]]


## Datatypes

In [20]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int32


In [21]:
import numpy as np
arr=np.array(['Apple','Banana','Orange'])
print(arr.dtype)

<U6


In [22]:
import numpy as np
arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


# Coverting datatype into existing arguments

In [24]:
import numpy as np
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


## Copy and View

In [26]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=32
print(arr)
print(x)

[32  2  3  4  5]
[1 2 3 4 5]


In [27]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=22
print(arr)
print(x)

[22  2  3  4  5]
[22  2  3  4  5]


## Shape

In [29]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
x=arr.shape
print(x)

(2, 4)


In [30]:
import numpy as np
arr=np.array([[1,2,3,4,5],[5,6,7,8,5]])
x=arr.shape
print(x)

(2, 5)


In [31]:
import numpy as np
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[2,5,7,8],[9,8,2,1]]])
x=arr.shape
print(x)

(2, 2, 4)


## Reshaping Arrays

#### 1D to 2D

In [34]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [35]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,4)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]]


### 1D to 3D

In [37]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Iteration

In [39]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
for x in arr:
    print(x)

1
2
3
4
5
6


In [40]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [41]:
import numpy as np
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[2,5,7,8],[9,8,2,1]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
2
5
7
8
9
8
2
1


In [42]:
import numpy as np
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[2,5,7,8],[9,8,2,1]]])
for x in np.nditer(arr):
    print(x)


1
2
3
4
5
6
7
8
2
5
7
8
9
8
2
1


## Joining

In [44]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([10,12,14,8])
arr=np.concatenate((arr1,arr2))
print(arr)

[ 1  2  3  4 10 12 14  8]


## Stacking

In [46]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([10,12,14,8])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[ 1 10]
 [ 2 12]
 [ 3 14]
 [ 4  8]]


In [47]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([10,12,14,8])
arr=np.hstack((arr1,arr2))
print(arr)

[ 1  2  3  4 10 12 14  8]


In [48]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([10,12,14,8])
arr=np.vstack((arr1,arr2))
print(arr)

[[ 1  2  3  4]
 [10 12 14  8]]


In [49]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([10,12,14,8])
arr=np.dstack((arr1,arr2))
print(arr)

[[[ 1 10]
  [ 2 12]
  [ 3 14]
  [ 4  8]]]


## Splitting

In [51]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [52]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [53]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [54]:
import numpy as np
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [55]:
import numpy as np
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,3,axis=1)
print(newarr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32)]


In [56]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr=np.hsplit(arr,3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## Sorting Arrays

In [58]:
import numpy as np
arr=np.array([3,2,5,1,0,5])
print(np.sort(arr))

[0 1 2 3 5 5]


In [59]:
import numpy as np
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [60]:
import numpy as np
arr=np.array([[3,2,5],[1,0,5]])
print(np.sort(arr))

[[2 3 5]
 [0 1 5]]


# Linear Algebra

### Dot product

In [63]:
import numpy as np
array1=np.array([1,3,5])
array2=np.array([2,4,6])
result=np.dot(array1,array2)
print(result)

44


In [64]:
import numpy as np
a=np.array([25,58,35])
b=np.array([5,2212,525])
x=np.dot(a,b)
print(x)

146796


### Inner product

In [66]:
import numpy as np
array1=np.array([[1,3],
                [5,7]])
array2=np.array([[2,4],
               [6,8]])
result=np.inner(array1,array2)
print(result)

[[14 30]
 [38 86]]


### Outer Product

In [68]:
import numpy as np
array1=np.array([1,3,5])
array2=np.array([2,4,6])
result=np.outer(array1,array2)
print(result)

[[ 2  4  6]
 [ 6 12 18]
 [10 20 30]]


### Determinant

In [70]:
import numpy as np
arr=np.array([[1,3],
             [5,7]])
result=np.linalg.det(arr)
print(result)

-7.999999999999998


### Linear eqn

In [72]:
import numpy as np
A=np.array([[2,4],
           [6,8]])
B=np.array([5,6])
x=np.linalg.solve(A,B)
print(x)

[-2.    2.25]


### Inverse

In [74]:
import numpy as np
A=np.array([[2,4],
           [6,8]])
x=np.linalg.inv(A)
print(x)

[[-1.    0.5 ]
 [ 0.75 -0.25]]


## Statistical Measures

In [4]:
import numpy as np
data=np.array([10,20,30,40,50])
mean=np.mean(data)
print("Mean:",mean)

Mean: 30.0


In [10]:
import numpy as np
data=np.array([10,20,5,40,50])
median=np.median(data)
print("Median:",median)

Median: 20.0


In [12]:
import numpy as np
data=np.array([10,20,30,40,50])
variance=np.var(data)
print("Variance:",variance)

Variance: 200.0


In [14]:
import numpy as np
data=np.array([10,20,30,40,50])
std_dev=np.std(data)
print("Standard deviation",std_dev)

Standard deviation 14.142135623730951


## Percentiles

In [17]:
import numpy as np
data=np.array([10,20,30,40,50,60,70,80,90,100])
p25=np.percentile(data,25)
print("25th percentile(Q1) :",p25)

25th percentile(Q1) : 32.5


In [19]:
import numpy as np
data=np.array([10,20,30,40,50,60,70,80,90,100])
p50=np.percentile(data,50)
print("50th percentile(median) :",p50)

50th percentile(median) : 55.0


In [21]:
import numpy as np
data=np.array([10,20,30,40,50,60,70,80,90,100])
p75=np.percentile(data,75)
print("75th percentile(Q3) :",p75)

75th percentile(Q3) : 77.5


## Interquartile Range

In [26]:
import numpy as np
data=np.array([10,20,30,40,50,60,30,80,70,90,60,52,32])
q1=np.percentile(data,25)
q3=np.percentile(data,75)
IQR=q3-q1
print("Q1:",q1)
print("Q3:",q3)
print("IQR:",IQR)

Q1: 30.0
Q3: 60.0
IQR: 30.0
